### ISSUE TITLE
Duplicate declarations of value in compiled "for key, value of"

### ISSUE THREAD

**Issue by KodyJKing** [krisnye/ion#5]
When targeting es6 'let' is used instead of 'var'. Re-declaring with 'let' causes an error and the code won't even run.

**Comment by krisnye** [comment]
Provide more detail. What is causing a redeclaration?

**Comment by krisnye** [comment]
a repro case with input ion and invalid output javascript with redeclarations would be good

**Comment by KodyJKing** [comment]
Fixed [here](https://github.com/krisnye/ion/commit/19deda619ca19e495298c177ca4c1526ff07aff5).
